Adding distintions between cd and ci, create bucket correctly

diff --git a/.cloudbees/workflows/bp-tf-ci.yaml b/.cloudbees/workflows/bp-tf-ci.yaml
--- a/.cloudbees/workflows/bp-tf-ci.yaml
+++ b/.cloudbees/workflows/bp-tf-ci.yaml
@@ -16,7 +16,7 @@ on:
 env:
   BUCKET_NAME_TF_STATE: cbci-eks-addon-bp
   AWS_REGION_TF_BUCKET: us-east-1
-  TAGS_TF_BUCKET: '[{Key=organization,Value=marketing2}]'
+  TAGS_TF_BUCKET: '[{Key=cb-owner,Value=professional-services},{Key=cb-user,Value=cb-platform},{Key=cb-purpose,Value=production shared cluster}]'
   AWS_ROLE_TO_ASSUME: "infra-admin-ci"
   TF_VAR_suffix: "ci"
   TF_VAR_aws_region: "us-west-2"
@@ -53,10 +53,16 @@ jobs:
       uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
       shell: bash
       run: |
-        aws s3api create-bucket \
-          --bucket "${{ env.BUCKET_NAME_TF_STATE }}" \
-          --region "${{ env.AWS_REGION_TF_BUCKET }}" \
-          --tagging "${{ env.TAGS_TF_BUCKET }}" || echo "Failed to put tags in ${{ env.BUCKET_NAME_TF_STATE }}"
+        set -x
+        if aws s3api head-bucket --bucket ${{ env.BUCKET_NAME_TF_STATE }} 2>/dev/null; then
+          echo "Bucket ${{ env.BUCKET_NAME_TF_STATE }} already exists."
+        else
+          echo "Bucket ${{ env.BUCKET_NAME_TF_STATE }} does not exist. Creating now..."
+          aws s3api create-bucket --bucket ${{ env.BUCKET_NAME_TF_STATE }} \
+              --region ${{ env.AWS_REGION_TF_BUCKET }}
+        fi
+        aws s3api put-bucket-tagging --bucket ${{ env.BUCKET_NAME_TF_STATE }} \
+              --tagging 'TagSet=${{ env.TAGS_TF_BUCKET }}'
 
   bp01:
     env:
@@ -123,7 +129,7 @@ jobs:
           --bucket "${{ env.BUCKET_NAME_TF_STATE }}" \
           --region "${{ env.AWS_REGION_TF_BUCKET }}" \
           --body blueprints/${{ env.ROOT }}/terraform.output \
-          --key ${{ env.ROOT }}/${{ env.ROOT }}.terraform.output || echo "Failed to put $body object in ${{ env.BUCKET_NAME_TF_STATE }}"
+          --key ${{ env.ROOT }}/${{ env.ROOT }}.ci.terraform.output || echo "Failed to put $body object in ${{ env.BUCKET_NAME_TF_STATE }}"
 
     - name: 01-getting-started - Validate
       uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
@@ -235,7 +241,7 @@ jobs:
           --bucket "${{ env.BUCKET_NAME_TF_STATE }}" \
           --region "${{ env.AWS_REGION_TF_BUCKET }}" \
           --body blueprints/${{ env.ROOT }}/terraform.output \
-          --key ${{ env.ROOT }}/${{ env.ROOT }}.terraform.output || echo "Failed to put $body object in ${{ env.BUCKET_NAME_TF_STATE }}"
+          --key ${{ env.ROOT }}/${{ env.ROOT }}.ci.terraform.output || echo "Failed to put $body object in ${{ env.BUCKET_NAME_TF_STATE }}"
 
     - name: 02-at-scale - Validate
       uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
